<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $skills = [
            [
                "id" => "1",
                "slug" => "laravel",
                "name" => "Laravel",
                "description" => "",
                "image_url" => "https://i.ibb.co/1T11111/rahmat.jpg",
                "icon_url" => "skills/01JWR7HBXBBX8MF9XSJ5JT4AR3.png",
                "percentage" => "90",
                "color" => "#0501d1",
                "type" => "coding",
            ],
            [
                "id" => "2",
                "slug" => "codeigniter",
                "name" => "Codeigniter",
                "description" => "",
                "image_url" => "https://i.ibb.co/1T11111/rahmat.jpg",
                "icon_url" => "skills/01JWR7JC20N3X01DYVGBXP5YZK.png",
                "percentage" => "95",
                "color" => "#fca61f",
                "type" => "coding",
            ],
            [
                "id" => "3",
                "slug" => "livewire",
                "name" => "Livewire",
                "description" => "",
                "image_url" => "https://i.ibb.co/1T11111/rahmat.jpg",
                "icon_url" => "skills/01JWR7KAV8306A8AKEND1QWMX6.svg",
                "percentage" => "85",
                "color" => "#1ecefc",
                "type" => "coding",
            ],
            [
                "id" => "4",
                "slug" => "jquery",
                "name" => "jQuery",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWR7M9PGXAJWDR75HC7DDX1Q.png",
                "percentage" => "95",
                "color" => "#f2ff00",
                "type" => "coding",
            ],
            [
                "id" => "5",
                "slug" => "next-js",
                "name" => "Next JS",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWR7NC1DFNR25K03VV4J5PBB.png",
                "percentage" => "50",
                "color" => "#3a9686",
                "type" => "coding",
            ],
            [
                "id" => "6",
                "slug" => "bootstrap",
                "name" => "Bootstrap",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWR7PE5HJ0PRY831ZAGM83ZY.png",
                "percentage" => "95",
                "color" => "#2231b8",
                "type" => "coding",
            ],
            [
                "id" => "7",
                "slug" => "nginx",
                "name" => "Nginx",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWR7QAK9FSP42MS9PJYFNG2H.png",
                "percentage" => "80",
                "color" => "#701e1e",
                "type" => "tool",
            ],
            [
                "id" => "8",
                "slug" => "linux",
                "name" => "Linux",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWR7RPXBZ76JXKGWKY3400MW.png",
                "percentage" => "85",
                "color" => "#226921",
                "type" => "tool",
            ],
            [
                "id" => "10",
                "slug" => "mysql",
                "name" => "MySQL",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRHWFDXM82ANHJD27H9J2RQ.png",
                "percentage" => "80",
                "color" => "#ffffff",
                "type" => "tool",
            ],
            [
                "id" => "11",
                "slug" => "google-cloud",
                "name" => "Google Cloud",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRHY7ZQPVYGB304EYEK48BV.png",
                "percentage" => "75",
                "color" => "#f5f18e",
                "type" => "tool",
            ],
            [
                "id" => "12",
                "slug" => "aws-ec2",
                "name" => "AWS EC2",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRHZHV05W8PKHAE6PDYGMMV.svg",
                "percentage" => "65",
                "color" => "#8687db",
                "type" => "tool",
            ],
            [
                "id" => "13",
                "slug" => "postgresql",
                "name" => "PostgreSQL",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRJ1FKFA64BHNFYMMGM6GMA.png",
                "percentage" => "75",
                "color" => "#edeb00",
                "type" => "tool",
            ],
            [
                "id" => "14",
                "slug" => "wordpress",
                "name" => "Wordpress",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRJEZ3NTQY35CCVF1VR4WK1.png",
                "percentage" => "80",
                "color" => "#84d482",
                "type" => "coding",
            ],
            [
                "id" => "15",
                "slug" => "redis",
                "name" => "Redis",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRJYQ985NYQWPWJXTYB3HJG.webp",
                "percentage" => "70",
                "color" => "#f0f0f0",
                "type" => "tool",
            ],
            [
                "id" => "16",
                "slug" => "corel-draw",
                "name" => "Corel Draw",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRK28XX8ASE7HG16DAN32KE.png",
                "percentage" => "85",
                "color" => "#53b6bd",
                "type" => "tool",
            ],
            [
                "id" => "17",
                "slug" => "photoshop",
                "name" => "Photoshop",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRK37BENF49V6GWZ4DZFWCN.png",
                "percentage" => "75",
                "color" => "#ff0000",
                "type" => "tool",
            ],
            [
                "id" => "18",
                "slug" => "filament",
                "name" => "Filament",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRKCESVGTQ46ZFJCYVN1P3X.avif",
                "percentage" => "75",
                "color" => "#faff00",
                "type" => "coding",
            ],
            [
                "id" => "19",
                "slug" => "docker",
                "name" => "Docker",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRKGPY10D901X21CY4F0YP6.webp",
                "percentage" => "65",
                "color" => "#b50505",
                "type" => "tool",
            ],
            [
                "id" => "20",
                "slug" => "github",
                "name" => "Github",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRKVPAAN9C8Q40KE1SC95SJ.png",
                "percentage" => "85",
                "color" => "#d1d1d1",
                "type" => "tool",
            ],
            [
                "id" => "21",
                "slug" => "gitlab",
                "name" => "Gitlab",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRKWK0BETRXYGSJYJZSXRXB.webp",
                "percentage" => "70",
                "color" => "#000000",
                "type" => "tool",
            ],
            [
                "id" => "22",
                "slug" => "networking",
                "name" => "Networking",
                "description" => "",
                "image_url" => "",
                "icon_url" => "",
                "percentage" => "80",
                "color" => "#258d9c",
                "type" => "knowledge",
            ],
            [
                "id" => "23",
                "slug" => "website-hosting",
                "name" => "Website Hosting",
                "description" => "",
                "image_url" => "",
                "icon_url" => "",
                "percentage" => "90",
                "color" => "",
                "type" => "knowledge",
            ],
            [
                "id" => "24",
                "slug" => "create-logo-design",
                "name" => "Create Logo Design",
                "description" => "",
                "image_url" => "",
                "icon_url" => "",
                "percentage" => "80",
                "color" => "",
                "type" => "knowledge",
            ],
            [
                "id" => "25",
                "slug" => "seo-website",
                "name" => "SEO Website",
                "description" => "",
                "image_url" => "",
                "icon_url" => "",
                "percentage" => "75",
                "color" => "",
                "type" => "knowledge",
            ],
            [
                "id" => "26",
                "slug" => "load-balancing",
                "name" => "Load Balancing App",
                "description" => "",
                "image_url" => "",
                "icon_url" => "",
                "percentage" => "75",
                "color" => "",
                "type" => "knowledge",
            ],
            [
                "id" => "27",
                "slug" => "deploy-app-to-vps",
                "name" => "Deploy App to VPS",
                "description" => "",
                "image_url" => "",
                "icon_url" => "",
                "percentage" => "85",
                "color" => "",
                "type" => "knowledge",
            ],
            [
                "id" => "28",
                "slug" => "email-hosting",
                "name" => "Email Hosting",
                "description" => "",
                "image_url" => "",
                "icon_url" => "",
                "percentage" => "85",
                "color" => "",
                "type" => "knowledge",
            ],
            [
                "id" => "29",
                "slug" => "payment-gateway-integration",
                "name" => "Payment Gateway Integration",
                "description" => "",
                "image_url" => "",
                "icon_url" => "",
                "percentage" => "85",
                "color" => "",
                "type" => "knowledge",
            ],
            [
                "id" => "30",
                "slug" => "uml-diagram",
                "name" => "UML Diagram",
                "description" => "",
                "image_url" => "",
                "icon_url" => "",
                "percentage" => "80",
                "color" => "",
                "type" => "knowledge",
            ],
            [
                "id" => "31",
                "slug" => "computer-installation",
                "name" => "Computer Installation",
                "description" => "",
                "image_url" => "",
                "icon_url" => "",
                "percentage" => "95",
                "color" => "",
                "type" => "knowledge",
            ],
            [
                "id" => "32",
                "slug" => "router-configuration",
                "name" => "Router Configuration",
                "description" => "",
                "image_url" => "",
                "icon_url" => "",
                "percentage" => "85",
                "color" => "",
                "type" => "knowledge",
            ]
        ];

        foreach ($skills as $skill) {
            \App\Models\Skill::create($skill);
        }

    }
}
