<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $skills = [
            [
                "id" => "1",
                "slug" => "laravel",
                "name" => "Laravel",
                "description" => "",
                "image_url" => "https://i.ibb.co/1T11111/rahmat.jpg",
                "icon_url" => "skills/01JWR7HBXBBX8MF9XSJ5JT4AR3.png",
                "percentage" => "90",
                "color" => "#0501d1",
                "type" => "coding",
                "created_at" => "2025-05-28 01:29:11",
                "updated_at" => "2025-06-02 15:02:01",
            ],
            [
                "id" => "2",
                "slug" => "codeigniter",
                "name" => "Codeigniter",
                "description" => "",
                "image_url" => "https://i.ibb.co/1T11111/rahmat.jpg",
                "icon_url" => "skills/01JWR7JC20N3X01DYVGBXP5YZK.png",
                "percentage" => "95",
                "color" => "#fca61f",
                "type" => "coding",
                "created_at" => "2025-05-28 01:29:11",
                "updated_at" => "2025-06-02 11:48:58",
            ],
            [
                "id" => "3",
                "slug" => "livewire",
                "name" => "Livewire",
                "description" => "",
                "image_url" => "https://i.ibb.co/1T11111/rahmat.jpg",
                "icon_url" => "skills/01JWR7KAV8306A8AKEND1QWMX6.svg",
                "percentage" => "85",
                "color" => "#1ecefc",
                "type" => "coding",
                "created_at" => "2025-05-28 01:29:11",
                "updated_at" => "2025-06-02 11:49:29",
            ],
            [
                "id" => "4",
                "slug" => "jquery",
                "name" => "jQuery",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWR7M9PGXAJWDR75HC7DDX1Q.png",
                "percentage" => "95",
                "color" => "#f2ff00",
                "type" => "coding",
                "created_at" => "2025-05-28 07:47:13",
                "updated_at" => "2025-06-02 15:02:27",
            ],
            [
                "id" => "5",
                "slug" => "next-js",
                "name" => "Next JS",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWR7NC1DFNR25K03VV4J5PBB.png",
                "percentage" => "50",
                "color" => "#3a9686",
                "type" => "coding",
                "created_at" => "2025-06-02 11:50:36",
                "updated_at" => "2025-06-02 11:50:36",
            ],
            [
                "id" => "6",
                "slug" => "bootstrap",
                "name" => "Bootstrap",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWR7PE5HJ0PRY831ZAGM83ZY.png",
                "percentage" => "95",
                "color" => "#2231b8",
                "type" => "coding",
                "created_at" => "2025-06-02 11:51:11",
                "updated_at" => "2025-06-02 11:51:11",
            ],
            [
                "id" => "7",
                "slug" => "nginx",
                "name" => "Nginx",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWR7QAK9FSP42MS9PJYFNG2H.png",
                "percentage" => "80",
                "color" => "#701e1e",
                "type" => "tool",
                "created_at" => "2025-06-02 11:51:40",
                "updated_at" => "2025-06-02 11:51:40",
            ],
            [
                "id" => "8",
                "slug" => "linux",
                "name" => "Linux",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWR7RPXBZ76JXKGWKY3400MW.png",
                "percentage" => "85",
                "color" => "#226921",
                "type" => "tool",
                "created_at" => "2025-06-02 11:52:25",
                "updated_at" => "2025-06-02 11:52:25",
            ],
            [
                "id" => "10",
                "slug" => "mysql",
                "name" => "MySQL",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRHWFDXM82ANHJD27H9J2RQ.png",
                "percentage" => "80",
                "color" => "#ffffff",
                "type" => "tool",
                "created_at" => "2025-06-02 14:49:14",
                "updated_at" => "2025-06-02 15:03:11",
            ],
            [
                "id" => "11",
                "slug" => "google-cloud",
                "name" => "Google Cloud",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRHY7ZQPVYGB304EYEK48BV.png",
                "percentage" => "75",
                "color" => "#f5f18e",
                "type" => "tool",
                "created_at" => "2025-06-02 14:50:12",
                "updated_at" => "2025-06-02 14:50:12",
            ],
            [
                "id" => "12",
                "slug" => "aws-ec2",
                "name" => "AWS EC2",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRHZHV05W8PKHAE6PDYGMMV.svg",
                "percentage" => "65",
                "color" => "#8687db",
                "type" => "tool",
                "created_at" => "2025-06-02 14:50:55",
                "updated_at" => "2025-06-02 14:50:55",
            ],
            [
                "id" => "13",
                "slug" => "postgresql",
                "name" => "PostgreSQL",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRJ1FKFA64BHNFYMMGM6GMA.png",
                "percentage" => "75",
                "color" => "#edeb00",
                "type" => "tool",
                "created_at" => "2025-06-02 14:51:58",
                "updated_at" => "2025-06-02 14:51:58",
            ],
            [
                "id" => "14",
                "slug" => "wordpress",
                "name" => "Wordpress",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRJEZ3NTQY35CCVF1VR4WK1.png",
                "percentage" => "80",
                "color" => "#84d482",
                "type" => "coding",
                "created_at" => "2025-06-02 14:55:02",
                "updated_at" => "2025-06-02 15:03:25",
            ],
            [
                "id" => "15",
                "slug" => "redis",
                "name" => "Redis",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRJYQ985NYQWPWJXTYB3HJG.webp",
                "percentage" => "70",
                "color" => "#f0f0f0",
                "type" => "tool",
                "created_at" => "2025-06-02 15:07:57",
                "updated_at" => "2025-06-02 15:07:57",
            ],
            [
                "id" => "16",
                "slug" => "corel-draw",
                "name" => "Corel Draw",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRK28XX8ASE7HG16DAN32KE.png",
                "percentage" => "85",
                "color" => "#53b6bd",
                "type" => "tool",
                "created_at" => "2025-06-02 15:09:53",
                "updated_at" => "2025-06-02 15:09:53",
            ],
            [
                "id" => "17",
                "slug" => "photoshop",
                "name" => "Photoshop",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRK37BENF49V6GWZ4DZFWCN.png",
                "percentage" => "75",
                "color" => "#ff0000",
                "type" => "tool",
                "created_at" => "2025-06-02 15:10:24",
                "updated_at" => "2025-06-02 15:10:24",
            ],
            [
                "id" => "18",
                "slug" => "filament",
                "name" => "Filament",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRKCESVGTQ46ZFJCYVN1P3X.avif",
                "percentage" => "75",
                "color" => "#faff00",
                "type" => "coding",
                "created_at" => "2025-06-02 15:15:27",
                "updated_at" => "2025-06-02 15:15:27",
            ],
            [
                "id" => "19",
                "slug" => "docker",
                "name" => "Docker",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRKGPY10D901X21CY4F0YP6.webp",
                "percentage" => "65",
                "color" => "#b50505",
                "type" => "tool",
                "created_at" => "2025-06-02 15:17:15",
                "updated_at" => "2025-06-02 15:17:55",
            ],
            [
                "id" => "20",
                "slug" => "github",
                "name" => "Github",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRKVPAAN9C8Q40KE1SC95SJ.png",
                "percentage" => "85",
                "color" => "#d1d1d1",
                "type" => "tool",
                "created_at" => "2025-06-02 15:23:46",
                "updated_at" => "2025-06-02 15:23:46",
            ],
            [
                "id" => "21",
                "slug" => "gitlab",
                "name" => "Gitlab",
                "description" => "",
                "image_url" => "",
                "icon_url" => "skills/01JWRKWK0BETRXYGSJYJZSXRXB.webp",
                "percentage" => "70",
                "color" => "#000000",
                "type" => "tool",
                "created_at" => "2025-06-02 15:24:15",
                "updated_at" => "2025-06-02 15:24:15",
            ],
        ];

        foreach ($skills as $skill) {
            \App\Models\Skill::create($skill);
        }

    }
}
