services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: resume
    container_name: resume
    restart: unless-stopped
    command: /bin/bash -c "/var/www/html/import-db.sh && php-fpm"
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - db

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"  # Ubah ke port 8080
      - "8443:443" # Ubah ke port 8443
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
    networks:
      - app-network
    depends_on:
      - app

  # PostgreSQL Service
  db:
    image: postgres:17
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "5433:5432"  # Ubah ke port 5433
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  pgdata:
    driver: local

